POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Pramod",
  "name": "Pramod Toleti",
  "password": "pramod_047",
  "gender": "male",
  "location": "India"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "Pramod",
  "oldPassword": "pramod_047",
  "newPassword": "pramodnew047"
}

###

